---
title: Network Canvas
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@networkcanvas.com
description: Welcome to the Network Canvas documentation website.
baseurl: ''
url: 'http://localhost:4000'
github_username: codaco
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-autoprefixer
search_enabled: true
aux_links:
  Network Canvas Home:
  - "//networkcanvas.com"
permalink: pretty
navigation:
  - title: About the Project
    url: //networkcanvas.com/about.html
  - title: Documentation
    url: /
  - title: Feedback
    url: //networkcanvas.com/feedback.html
